# Generated by Django 4.2.16 on 2024-10-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_lichsu_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='dust',
            field=models.FloatField(default=50),
        ),
    ]
